mp.messaging.incoming.words-in.address=words
mp.messaging.outgoing.words-out.address=words
quarkus.datasource.db-kind=h2
quarkus.datasource.users.username=sa
quarkus.datasource.users.password=password
quarkus.datasource.users.jdbc.url=jdbc:h2:mem:mydb
quarkus.datasource.users.jdbc.max-size=11