# Configurazione per Artemis
quarkus.artemis.url=tcp://localhost:61616
quarkus.artemis.username=admin
quarkus.artemis.password=admin

# Configurazione per Reactive Messaging con Artemis
mp.messaging.connector.smallrye-artemis.host=localhost
mp.messaging.connector.smallrye-artemis.port=61616
mp.messaging.connector.smallrye-artemis.username=admin
mp.messaging.connector.smallrye-artemis.password=password

# Configurazione di un canale di messaggistica che utilizza Artemis

# Configurazione di un canale di messaggistica che utilizza Artemis
mp.messaging.incoming.item-in.connector=smallrye-amqp
mp.messaging.incoming.item-in.destination=item
#Serve?Siccome address contiene una cosa sola non serve: mp.messaging.incoming.item-in.address=item
mp.messaging.incoming.item-in.durable=false  # Messaggi non persistenti per questo esempio

mp.messaging.outgoing.item-out.connector=smallrye-amqp
#Serve?Siccome address contiene una cosa sola non serve: mp.messaging.outgoing.item-out.address=item
mp.messaging.outgoing.item-out.destination=item
mp.messaging.outgoing.item-out.durable=false  # Messaggi non persistenti per questo esempio


mp.messaging.incoming.words-in.address=words
mp.messaging.outgoing.words-out.address=words

quarkus.datasource.db-kind=h2
quarkus.datasource.users.username=sa
quarkus.datasource.users.password=password
quarkus.datasource.users.jdbc.url=jdbc:h2:mem:mydb
quarkus.datasource.users.jdbc.max-size=11